---
- name: "Install nginx"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: install nginx
      yum:
        state: present
        name: nginx

    - name: start nginx
      service:
        name: nginx
        state: started

    - name: start on boot
      service:
        name: nginx
        enabled: true