---
- name: "Install nginx"
  hosts: localhost
  connection: local
  become: yes
  tasks:    
    - name: base configuration | Packages
      apt:
        state: present
        name: "{{ item }}"
      with_items:
        - wget
        - telnet
        - epel-release
    
    - name: install nginx
      apt:
        state: present
        name: nginx

    - name: start nginx
      service:
        name: nginx
        state: started
    
    - name: start on boot
      systemd:
        name: nginx
        enabled: true